# Generated by Django 5.1.2 on 2024-12-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_project_team_alter_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductivity',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
