# Generated by Django 5.1.2 on 2024-12-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_remove_userproductivity_years_of_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='workload',
            field=models.FloatField(default=0.0),
        ),
    ]
