# Generated by Django 5.1.2 on 2024-12-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_userprofile_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
