# Generated by Django 5.1.2 on 2024-12-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0006_task_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='meeting_types',
            field=models.TextField(default='[]'),
        ),
    ]
