# Generated by Django 5.1.4 on 2024-12-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0007_alter_project_meeting_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='meeting_frequency',
            field=models.IntegerField(default=0),
        ),
    ]
