# Generated by Django 5.1.2 on 2024-11-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0007_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
